%YAML:1.0
---

# 端口列表，can端口名称必须包含‘can’，串口必须包含‘tty’
port_list:
  - can0
  - can1

# 给每个端口绑定其收发的包id
# 如果尝试收发没有列在这里的id，代码会崩
# 重复设置id时，只会绑定到最开始包含该id都端口
id_list: 
  - port: can0
    id:
      - 0x301
      - 0x312
      - 0x313
      - 0x314
      - 0x315
      - 0x316
      - 0x345
      - 0x321
  - port: can1
    id:
      - 0x321
      - 0x316
      - 0x322
      - 0x323
      - 0x324
      - 0x325
      - 0x344
      - 0x334
      - 0x345

# 调度组
# 重复设置端口所在组时，只会设置为最后包含该端口的组
shedule_group:
  - 
    - can0
    - can1
    - can2
    - can5
  -
    - can3
    - can4