%YAML:1.0
---

can: 
  - port: can0
    id:
      - 0x312
      - 0x313
      - 0x314
      - 0x315
      - 0x316
      # - 0x321
  - port: can1
    id:
      - 0x321
      - 0x322
      - 0x323
      - 0x324
      - 0x325
